# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdeps < Formula
  desc "Git dependencies manager. Simplified version of git submodules."
  homepage "https://github.com/Nelonn/gitdeps"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.5/gitdeps_0.0.5_darwin_amd64.zip"
      sha256 "fb5133ec393adc6fc874fe2f0a82e5292845428e4cefac2789cd3b4d7d6d7d0a"

      def install
        bin.install "gitdeps"
      end
    end
    on_arm do
      url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.5/gitdeps_0.0.5_darwin_arm64.zip"
      sha256 "e17ce1e7071903b1ca6c7caa40d0713804f30dd58a59ba10fc41fd6904b96ee4"

      def install
        bin.install "gitdeps"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.5/gitdeps_0.0.5_linux_amd64.tar.gz"
        sha256 "61f44682afde4c2bda5cfed649bfb9b067e529f006ba8df39482feec9618d7b0"

        def install
          bin.install "gitdeps"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.5/gitdeps_0.0.5_linux_armv6.tar.gz"
        sha256 "08a39a67332177c1f8894f9d7f8b41a09260b6b8a8388fedb761574c6e036837"

        def install
          bin.install "gitdeps"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.5/gitdeps_0.0.5_linux_arm64.tar.gz"
        sha256 "7b2fc124fb3c1cc792a10f91e179c42990452fafb61c694c566049a6363c2199"

        def install
          bin.install "gitdeps"
        end
      end
    end
  end
end
