# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdeps < Formula
  desc "Git dependencies manager. Simplified version of git submodules."
  homepage "https://github.com/Nelonn/gitdeps"
  version "0.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.6/gitdeps_0.0.6_darwin_amd64.zip"
      sha256 "1989b58d609dd07df5f4407b3002d5acff2d8704e2e91095057aeeea5398adfa"

      def install
        bin.install "gitdeps"
      end
    end
    on_arm do
      url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.6/gitdeps_0.0.6_darwin_arm64.zip"
      sha256 "202a805056cb535fd333a9a9135b8b446b025572a76bbcdb75ab1422493bfa11"

      def install
        bin.install "gitdeps"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.6/gitdeps_0.0.6_linux_amd64.tar.gz"
        sha256 "071095edeeae734d3e03f04709acae9737352663b9b340c2a125f4860cb3a319"

        def install
          bin.install "gitdeps"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.6/gitdeps_0.0.6_linux_armv6.tar.gz"
        sha256 "0de7c7085856f88b5784d6b44b59c65a0acfe266dfe074a4a9e44aec4030e902"

        def install
          bin.install "gitdeps"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Nelonn/gitdeps/releases/download/v0.0.6/gitdeps_0.0.6_linux_arm64.tar.gz"
        sha256 "133a10abdd9d065b92155af1d9344a99825d0416c5bd52e2512946432ad708c6"

        def install
          bin.install "gitdeps"
        end
      end
    end
  end
end
